Repository MoriARosland/elevator-system, pull requests merged in 2024-03, with the labels that each got.

#12 feat: single elevator module
  src/elev/elev.go
  src/elevator/elevator.go
  src/elevator/types.go
  src/fsm/fsm.go
  src/main.go
  src/network/broadcast.go
  src/network/watchdog.go
  src/requests/requests.go
  src/timer/timer.go
  src/types/types.go
Labels: feature

#14 feat: add send function using udp
  go.work
  src/network/sender.go
Labels: feature

#16 feat: udp secure send
  src/main.go
  src/network/broadcast.go
  src/network/localip.go
  src/network/sender.go
  src/network/watchdog.go
  src/types/types.go
Labels: feature

#21 feat: move side effects out of fsm
  src/elev/elev.go
  src/fsm/fsm.go
  src/main.go
  src/network/receiver.go
  src/requests/requests.go
  src/types/types.go
Labels: enhancement, feature

#20 feat: setting lights
  src/elev/elev.go
  src/main.go
  src/requests/requests.go
  src/types/types.go
Labels: enhancement, refactor

#22 feat: clearing orders in correct direction
  src/requests/requests.go
Labels: feature

#27 feat: time to served
  src/fsm/costFunction.go
  src/types/types.go
Labels: feature

#32 feat: improve secure send
  src/elev/elev.go
  src/main.go
  src/network/messages.go
  src/network/sender.go
  src/types/elev.go
  src/types/network.go
Labels: enhancement, refactor, feature

#34 feat: order assignment and clearing
  go.work
  lib/driver-go-master/go.mod
  lib/go-reuseport-0.4.0/go.mod
  src/elev/elev.go
  src/fsm/costFunction.go
  src/go.mod
  src/main.go
  src/network/messages.go
  src/network/sender.go
  src/network/watchdog.go
  src/types/elev.go
  src/types/network.go
  src/utils.go
Labels: enhancement, feature

#36 feat: new timer package
  src/elev/elev.go
  src/main.go
  src/network/messages.go
  src/timer/timer.go
  src/types/timer.go
Labels: feature

#37 feat: order synchronisation
  src/elev/elev.go
  src/fsm/fsm.go
  src/main.go
  src/network/localip.go
  src/network/messages.go
  src/network/watchdog.go
  src/types/network.go
  src/utils.go
Labels: refactor, feature

#39 feat: door obstruction order reassignment
  src/elev/elev.go
  src/main.go
  src/network/messages.go
  src/timer/timer.go
  src/types/elev.go
  src/types/network.go
Labels: enhancement, feature

#41 feat: stuck between floors order reassignment
  src/elev/elev.go
  src/main.go
  src/types/elev.go
  src/utils.go
Labels: enhancement, feature

#40 feat: order reassignment on disconnect
  src/elev/elev.go
  src/main.go
  src/network/messages.go
  src/network/watchdog.go
Labels: feature

#44 feat: disconnected mode
  src/elev/elev.go
  src/main.go
  src/network/broadcast.go
  src/network/localip.go
  src/network/messages.go
  src/network/receiver.go
  src/network/sender.go
  src/network/watchdog.go
  src/types/elev.go
  src/types/network.go
Labels: feature

#47 feat: single elevator mode
  .gitignore
  src/elev/elev.go
  src/main.go
  src/network/receiver.go
  src/network/sender.go
  src/network/watchdog.go
  src/types/elev.go
Labels: enhancement, feature

#48 fix: prevent bidding when stuck
  src/main.go
Labels: bug

#59 refactor: msg handling
  src/elev/elev.go
  src/elev/handlers.go
  src/elev/init.go
  src/main.go
  src/network/msgUtils.go
  src/types/elev.go
  src/utils.go
Labels: refactor

#63 feat: disconnected mode
  src/elev/elev.go
  src/elev/handlers.go
Labels: feature

#61 feat: message loop counter
  src/elev/elev.go
  src/elev/handlers.go
  src/main.go
  src/network/msgUtils.go
  src/types/network.go
Labels: feature
